env:
  browser: true
  es6: true
extends:
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: { 'space-before-function-paren': 0, 'prettier/prettier': 'error' }
plugins: prettier
